### ISSUE TITLE
Code needs some work on properly saving articles in multiple languages

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/google-app-scripts#117]
This is a big task, so I don't want to get started on it until after the break next week. The work I've been doing around changing which article a document is linked to has been showing me quite a few places where things are brittle or just not thought through enough - this is great, it's good to catch this stuff.

One thing this process has made clear to me is that how we're handling multilingual content needs more work.

Example: I tried manually associating a document with an existing article in a locale I had just added to webiny. So, this article _does_ exist, in `en-US`, and I chose to link it to the article in locale `es`. 

What happened is the existing article contents got replaced by the document contents in `es` locale; i mean, the american english content disappeared.

```
          {
            "id": "5f87b5c13d422f0008b3e129",
            "headline": {
              "values": [
                {
                  "value": "Manually Associate This Article",
                  "locale": "5f9b54744f82710007c4303c"
                }
              ]
            }
//...
```

Locale ID#5f9b54744f82710007c4303c is es/spanish. Previously this article's headline had the en-US localeID for headline.

I think we need to do the following for multilingual articles:

1. make sure we've i18n'ed the right fields
  1a) sidenote: should slugs be i18n? ditto category slugs. they're not now. making them i18n would complicate matters...
2. request article data, merge in the current document i18n values; we want to avoid replacing `headline.values[]` for instance and instead append the new locale or update the existing data for that locale.
3. then save the article
4. take a fresh look at how we're requesting article contents for the frontend

**Comment by TylerFisher** [comment]
I don't think slugs should be i18n. Not sure what impact that would have on SEO.

**Comment by jacqui** [comment]
Good point about how to replace content. I think I need to take another look at how the webiny content admin handles doing these requests first.
