### ISSUE TITLE
Can't update headline, authors, tags

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#130]
While trying to publish a new article, a lot of data was not getting updated.

I originally titled [this document](https://docs.google.com/document/d/1orm0MhsRk0MaZQ1t5yJgDN2o17VUQ2epzWfyp90Wuac/edit?addon_dry_run=AAnXSK83C9AWHLGGEEs2jPb-tn1WkyeubZebwaQrN3x4q-Up7LCeCmT-vtLNWClIJ2gZdqQPQs7mS-VhhwWQZ3C-XRtYQIX7hUvgWvrNh0F-FrWhrGWCFT6pJ9yt-NDJzgdFWUtAemBG) "Locale PR". After pulling in the story, I updated the document name to the headline. However, the slug and headline of the story stay stuck at "Locale PR" despite me never publishing the article with that title.

I also cannot add any authors or tags. I can add them in the form and submit them, but they do not appear on the site, and if I reopen the sidebar, there aren't any authors or tags associated.

**Comment by jacqui** [comment]
Sorry about that - I found the issues around:

* headline
* tags
* authors
* locale

... and was able to fix them all. I verified this works on:

* a new and different doc than the one you were using
* and then, on the Kensington Voting Guide doc you tried with

I updated the PR with details (https://github.com/news-catalyst/google-app-scripts/pull/124#issuecomment-731849644) - my one question is, when the headline changes, should the slug automatically update as well?
