### ISSUE TITLE
Preview after publishing an article publishes the previewed changes

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#153]
I'm not sure if this is expected behavior, though I can see why this is happening. Is there any way to preview new content on an already published story? This seems tricky given our API structure...

to-do:

* [x] add a createArticleFrom function that revisions article content
* [x] add version, latestVersion, parent fields on Article
* [x] add a publish function to graphql API (https://github.com/webiny/webiny-js/blob/bfb0d4606a160d771d3fa6b01775e7a94d6ec241/packages/api-headless-cms/src/content/plugins/utils/resolvers/manage/resolvePublish.ts)
* [x] get and list article functionality should return most recent version (latestVersion)? check webiny implementation
* [x] update google docs add-on to use createArticleFrom, publish functions
* [x] update preview to use createArticle or createArticleFrom without publish flag

**Comment by jacqui** [comment]
Argh yeah. I think Webiny handles it by referring to a version ID, where the content has a parent ID but each version has its own published status. I'm wondering if there's a way for us to recreate that logic in a straightforward & reliable manner. 

On the front-end, we'd need to be careful when doing article lookups by slug to grab the most recent version that is published.

**Comment by jacqui** [comment]
I'm having a look at how Webiny handles versioning content in the code:

* `latestVersion` is a boolean set to true on the most recent version of the content
* `version` is a unique value (not sure how it's generated yet)
* `parent` is the version ID of the parent content

Here's the beforeCreate hook that sets these fields ([source](https://github.com/webiny/webiny-js/blob/bfb0d4606a160d771d3fa6b01775e7a94d6ec241/packages/api-form-builder/src/plugins/models/Form/withLatestVersion.ts#L7-L28)):

```
        withHooks({
            async beforeCreate() {
                this.latestVersion = true;

                if (this.version > 1) {
                    const removeCallback = this.hook("afterCreate", async () => {
                        const previousLatestForm = await this.constructor.findOne({
                            query: {
                                parent: this.parent,
                                latestVersion: true,
                                version: { $ne: this.version }
                            }
                        });

                        if (previousLatestForm) {
                            previousLatestForm.latestVersion = false;
                            await previousLatestForm.save();
                        }
                        removeCallback();
                    });
                }
            },
```

**Comment by jacqui** [comment]
Looks like version is basically an auto-incremented number ([source](https://github.com/webiny/webiny-js/blob/bfb0d4606a160d771d3fa6b01775e7a94d6ec241/packages/api-headless-cms/src/content/plugins/utils/createDataModel.ts#L361-L372)):

```
            async getNextVersion() {
                const revision = await Model.findOne({
                    query: { parent: this.meta.parent, deleted: { $in: [true, false] } },
                    sort: { version: -1 }
                });

                if (!revision) {
                    return 1;
                }

                return revision.meta.version + 1;
            }
```

**Comment by jacqui** [comment]
Adding a link to this `onSet` code from webiny showing how they handle setting the published dates - interesting, I didn't know we could do this:

https://github.com/webiny/webiny-js/blob/bfb0d4606a160d771d3fa6b01775e7a94d6ec241/packages/api-form-builder/src/plugins/models/form.model.ts#L62-L91

**Comment by jacqui** [comment]
Also, how other revisions are handled - though I need to figure a bit more about this:

https://github.com/webiny/webiny-js/blob/bfb0d4606a160d771d3fa6b01775e7a94d6ec241/packages/api-form-builder/src/plugins/models/form.model.ts#L167-L185

**Comment by TylerFisher** [comment]
Okay, this is all really interesting. I think being clear on how we publish content vs. preview content is super important considering we could be dealing with high-secrecy investigative work. Making sure users aren't inadvertently publishing things seems like a high priority to me. I'm going to put figuring this out into this sprint.

**Comment by jacqui** [comment]
Adding onto this - we'll need to change how we create vs update content, unfortunately, going back to the `createArticle` vs `createArticleFrom`. As the google add-on does separate these functions still, this shouldn't be a super painful change. 

Implementing it on the API side is where the trickiness comes into play.

Here's the source for creating a new revision from webiny:

https://github.com/webiny/webiny-js/blob/bfb0d4606a160d771d3fa6b01775e7a94d6ec241/packages/api-form-builder/src/plugins/graphql/formResolvers/createRevisionFrom.ts
