### ISSUE TITLE
Update getArticleMeta for Hasura

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/google-app-scripts#197]
This function needs to:

* check folder structure:
  * if `pages` and stored ID, look up page by ID
  * if `pages` and no stored ID, look up page by google doc ID
  * if `articles` and ID, look up article by ID
  * otherwise look up article by document ID
* return the following data:

```
  var articleMetadata = {
    accessToken: accessToken,
    allAuthors: allAuthors,
    allTags: allTags,
    articleAuthors: articleAuthors,
    articleID: articleID,
    articleTags: articleTags,
    authorSlugs: authorSlugsValue,
    awsAccessKey: awsAccessKey,
    awsSecretKey: awsSecretKey,
    awsBucket: awsBucket,
    availableLocales: availableLocales,
    googleDocs: googleDocsInfo,
    categories: categories,
    categoryID: categoryID,
    categoryName: categoryName,
    contentApi: contentApi,
    customByline: customByline,
    documentType: documentType,
    firstPublishedOn: firstPublishedOn,
    lastPublishedOn: lastPublishedOn,
    localeID: selectedLocaleID,
    localeName: selectedLocaleName,
    locales: locales,
    previewUrl: previewUrl,
    previewSecret: previewSecret,
    headline: headline,
    published: published,
    publishingInfo: publishingInfo,
    publishUrl: publishUrl,
    slug: slug,
    seo: seoData,
    republishUrl: republishUrl
  };
```
  
The current function does _a_ _lot_ of document property setting and is confusing. I propose commenting all of that out at first to see if it's actually necessary.

**Comment by TylerFisher** [comment]
Asking because I'm genuinely unclear: is it necessary to store the AWS stuff at the article level?

**Comment by jacqui** [comment]
The AWS settings are stored at an organisation level, but they're retrieved per-document. Actually, though, I'm not sure why I'm returning them in this article metadata call, so I'll look into that while I'm rewriting this today.

I'm thinking this function should be returning enough data for the publishing tools sidebar to render, which would be:

* organisation locales
* current article locale
* article slug
* headline
* search title, description
* facebook title, description
* twitter title, description
* authors: org authors, article authors
* tags: org tags, article tags
* categories: org categories, article category
* published? and dates
* (in a later step, the translate-this-article stuff, but I'll hold off on that to keep things simple)
