### ISSUE TITLE
Sidebar not finding correct translations

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#226]
[This story](https://docs.google.com/document/d/1UvFCWjjPc8cxKInUhbRtsH9tygkOCLyKvd76BgpO-Yc/edit?addon_dry_run=AAnXSK8weoPoGRUFxw550B_LesKwCctcGzEQtq2f0vfmTCs2dxQEvQus51IlNN5xVX-Rknf0fJeuRmv_041hlGC5LSqGPeeCuMw5fjLWpfJn8iqvuT2_F23wUBaBwRXsgt6SH_ZSc7P3) looks as if no translation has been published. It retrieves translation with an ID `69`, which isn't published, however, in the database, there's a translation with an ID `72` that is published. Theoretically, the query should return `72`, but that doesn't appear to be happening.

I suppose this also raises the question: how do we handle articles that have been published but have a newer preview? [This section of the get article query](https://github.com/news-catalyst/google-app-scripts/blob/master/Code.js#L1167-L1182) returns the translation with the highest ID. Maybe we should get all translations and sort it out ourselves? Get all translations ordered by ID, get the latest one regardless of publish status, but also check to see if any are published and render the state as necessary.

**Comment by jacqui** [comment]
My last PR #229 should have fixed the first issue here - sidebar not getting the right translation.

As for the second, this is a matter of displaying the most recent translation content, whether published or not, while also displaying the correct publishing information.

We briefly discussed that on slack. My idea is to make a new join table called `published_articles`:

* article_id
* article_translation_id
* locale_code

This table would have one record per article + locale; the article_translations table can have multiple records for the same article + locale. The published dates would come from the corresponding translation record. 

I think that making this happen involves:

1. creating the new table in Hasura with permissions and relationships defined
2. adding functionality to the publish article feature (sidebar): this should do an upsert to this table updating the translation ID for the given locale & article.
3. update the queries used in the sidebar to grab the right translation record for displaying published status (dates, true/false)
4. update the front-end: previewed articles should still display the correct published dates, right?

**Comment by TylerFisher** [comment]
Yeah, previewed articles should display the correct publish dates. I like this approach. Keeps it relational and lets us more easily get useful data.
