### ISSUE TITLE
Publishing fails

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#227]
May be related to #226, not sure. When I try to publish [this story](https://docs.google.com/document/d/1UvFCWjjPc8cxKInUhbRtsH9tygkOCLyKvd76BgpO-Yc/edit?addon_dry_run=AAnXSK8weoPoGRUFxw550B_LesKwCctcGzEQtq2f0vfmTCs2dxQEvQus51IlNN5xVX-Rknf0fJeuRmv_041hlGC5LSqGPeeCuMw5fjLWpfJn8iqvuT2_F23wUBaBwRXsgt6SH_ZSc7P3) (which should be republishing), I get this error. 

```
data: {"errors":[{"extensions":{"path":"$.variableValues","code":"validation-failed"},"message":"expecting a value for non-nullable variable: locale_code of type: String! in variableValues"}]}

TypeError: Cannot read property 'insert_articles' of undefined
    at hasuraHandlePublish(Code:975:31)
```

**Comment by jacqui** [comment]
This is fixed:

* published articles now show "re-publish" and "unpublish" buttons in the sidebar
* publishing works without reporting this or another bug.
