### ISSUE TITLE
Predefined form fields are not filling

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#228]
Related to #226, my sidebar is not loading values from the database even with the translation it received. Translation `69` has a headline, search description, etc., but none of those values are filled in when I open the sidebar. 

<img width="299" alt="Screen Shot 2021-02-22 at 10 54 17 AM" src="https://user-images.githubusercontent.com/1077075/108733234-544f5d00-74fc-11eb-922a-8fad04c7f375.png">

**Comment by jacqui** [comment]
This should be fixed in the most recent PR.
