### ISSUE TITLE
Return preview/publish URLs at their production URLs, not localhost

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#253]
Tried to get this myself but I actually can't find where this happens.

Since we're moving Mariko onto this system soon, we need this to work for her.

**Comment by jacqui** [comment]
Ah, yeah this is a bit hidden. Both of these URLs are set in the add-on config:

<img width="297" alt="Screen Shot 2021-03-09 at 7 42 46 am" src="https://user-images.githubusercontent.com/3397/110379563-1846fb00-80ab-11eb-86ec-cba89b833dae.png">

So you open "Admin Tools", toggle the config form, set the values and "Save Config"

I'll update both now.

**Comment by jacqui** [comment]
I've updated both URLs to point at https://next-tinynewsdemo.vercel.app/ (and https://next-tinynewsdemo.vercel.app/api/preview)
