### ISSUE TITLE
Update add-on name

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/google-app-scripts#265]
<img width="643" alt="Screen Shot 2021-05-05 at 9 59 17 am" src="https://user-images.githubusercontent.com/3397/117083684-97de0700-ad88-11eb-87fa-91376dd4287b.png">

Just noticed that the menu item is still set to "Tiny News Webiny Publishing Sidebar" - what do we want to call this menu item for our tiny news orgs?

"Tiny News Publishing"? "Tiny News Publishing Tools"?

**Comment by TylerFisher** [comment]
I think consolidating around the `TinyCMS` name is good. `TinyCMS Publishing Tools`?
