### ISSUE TITLE
Add sources to sidebar

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#269]
Below all of the SEO/social metadata, default to showing a single set of form fields for one source. Below that, add a `+ add source` button that appends another set of form fields.

Fields are:

- Name (Text field)
- Affiliation (Text field)
- Race (select field, see [TNC application](https://docs.google.com/document/d/1bqaTi234myIxNzHBO3AqqxWW6MxArXcCvE-64Jvk7Jk/edit#) for options)
- Ethnicity (select field, see [TNC application](https://docs.google.com/document/d/1bqaTi234myIxNzHBO3AqqxWW6MxArXcCvE-64Jvk7Jk/edit#) for options)
- Gender (select field, see [TNC application](https://docs.google.com/document/d/1bqaTi234myIxNzHBO3AqqxWW6MxArXcCvE-64Jvk7Jk/edit#) for options)
- Sexual orientation (select field, see [TNC application](https://docs.google.com/document/d/1bqaTi234myIxNzHBO3AqqxWW6MxArXcCvE-64Jvk7Jk/edit#) for options)
- Age (select field, see [TNC application](https://docs.google.com/document/d/1bqaTi234myIxNzHBO3AqqxWW6MxArXcCvE-64Jvk7Jk/edit#) for options)
- Zip code (Text field)
- Contact email address (Text field)
- Contact phone number (Text field)
- Role in story (Select field, options are: Quoted, mentioned, background. Maybe more to come.)

All fields except name are optional, but one of contact email/phone number must be submitted.

On publish, if no sources are available, show an alert window warning users they are trying to submit a story with no sources. They can continue, but we want this extra bit of friction.

**Comment by jacqui** [comment]
@TylerFisher I'm wondering if the "prefer to self-describe" option makes sense in this context? Also, would something akin to "not sure", "unknown", and/or "other" make sense for a reporter who's describing a source's ethnicity (or race, or gender, etc)? 

The fields with `<select>` options are not required, so perhaps omitting is the way of saying you don't know or "other"?

**Comment by TylerFisher** [comment]
Ah, yeah, prefer to self-describe doesn't make much sense here. Let's go with "Other".
