### ISSUE TITLE
List nodes getting duplicated

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#286]
This section in a Google Doc
<img width="245" alt="Screen Shot 2021-07-01 at 2 02 57 PM" src="https://user-images.githubusercontent.com/1077075/124170143-10093600-da75-11eb-9905-e758f3be677a.png">

is coming through the API as 
<img width="554" alt="Screen Shot 2021-07-01 at 2 03 51 PM" src="https://user-images.githubusercontent.com/1077075/124170744-cb31cf00-da75-11eb-9c4e-217d684bc0cf.png">

and rendered as
<img width="210" alt="Screen Shot 2021-07-01 at 2 08 32 PM" src="https://user-images.githubusercontent.com/1077075/124170776-d5ec6400-da75-11eb-8661-de3c0aad8c14.png">

**Comment by TylerFisher** [comment]
FWIW, I was able to fix this by removing and retyping the list. Not sure how to replicate in the future, but I needed this fixed today before I had time to fully investigate.

**Comment by jacqui** [comment]
I tried to replicate the issue today but wasn't able to. We can revisit if it happens again - if it does, would be great if I could get access to the problematic document.

**Comment by jacqui** [comment]
I think the recent work done on lists, including test coverage, helps to ensure un/ordered lists are handled correctly in the document parsing. Closing this.
