### ISSUE TITLE
Script to republish all published articles within a publication

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#296]
This is for the future, not now, but important nonetheless.

Going through and republishing everything to pick up the new main image handling was a bit of a hassle. Would be completely unmanageable for many orgs with many articles.

**Comment by jacqui** [comment]
Thinking through how to do this...

Republishing all published articles means processing each google doc (contents + metadata as defined in the sidebar). This allows any changes in the parsing, formatting, or storing logic to be picked up.

1. It's straightforward to get a list of all published articles in an organisation - basically a slight modification of [this query for the articles archive page](https://github.com/news-catalyst/next-tinynewsdemo/blob/main/lib/articles.js#L1606-L1643)

2. Modify that query to include associated google docs:

```
    article_google_documents {
      google_document {
        document_id
        url
      }
    }
```

3. Armed with a list of google document IDs, now we need to process each of them. I figure this republish would be triggered from... the admin sidebar, as we need access to Google Apps Script. It looks like it might support [opening a different Google Doc by ID](https://developers.google.com/apps-script/reference/document/document-app#openbyidid) but I need to test that.
4. Then the script needs to grab the document contents and process them
5. Not sure how to get the metadata from the sidebar in each as that's definitely not accessible.
6. So perhaps the script needs to load the most recent article translation, grab the search/facebook/twitter title & description, then fill those values in for the new translation.

Are we fine with publishing the latest contents of each doc? I mean, it is possible that a document was published, then modified and not published yet. It might be possible to query for only articles where the most recent translation is published...

**Comment by jacqui** [comment]
Good news - I am able to open other google documents from the sidebar of one! 

However, some of the code needs further work. Just logging this here for my notes so I know what to focus on when I start on this again:

```
storing image list: {"kix.o9vbvwqrgzm":"http://tnc-test-upload-bucket.s3.amazonaws.com/oaklyn/franny-lous-porch-starts-a-gofundme-to-buy-their-building/imagekix.o9vbvwqrgzm.png","kix.5w1vfmw9cv36":"http://tnc-test-upload-bucket.s3.amazonaws.com/oaklyn/franny-lous-porch-starts-a-gofundme-to-buy-their-building/imagekix.5w1vfmw9cv36.png","kix.9vuyqtpvub8c":"http://tnc-test-upload-bucket.s3.amazonaws.com/oaklyn/franny-lous-porch-starts-a-gofundme-to-buy-their-building/imagekix.9vuyqtpvub8c.png","kix.v0t1eqdgqtel":"http://tnc-test-upload-bucket.s3.amazonaws.com/oaklyn/franny-lous-porch/imagekix.v0t1eqdgqtel.png","kix.7oe81eyfmyz2":"http://tnc-test-upload-bucket.s3.amazonaws.com/oaklyn/franny-lous-porch/imagekix.7oe81eyfmyz2.png","kix.56ffuyz1ndm0":"http://tnc-test-upload-bucket.s3.amazonaws.com/oaklyn/franny-lous-porch/imagekix.56ffuyz1ndm0.png","kix.rokfk7nr0sud":"http://tnc-test-upload-bucket.s3.amazonaws.com/oaklyn/franny-lous-porch/imagekix.rokfk7nr0sud.png","kix.fotny6o45s1c":"http://tnc-test-upload-bucket.s3.amazonaws.com/oaklyn/franny-lous-porch/imagekix.fotny6o45s1c.png"}
```

Image uploading and cache of urls needs to use each article's slug instead of relying on the active document article slug. I'm seeing each document use the "Franny Lou" slug instead of the appropriate one for that article.

Additionally, the metadata like search title is not available, so the script will have to look up that info for each article as well, then merge it in with the latest document contents before saving in the database/hasura.
