### ISSUE TITLE
Publishing a new document with a used slug overwrites the existing article

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#338]
In migrating Crystal's content, she had two articles that ended up returning the same slug. One was headlined "The 2021 West Virginia Black Legislative Agenda?", the next piece did not have a question mark. 

The right behavior would be one of two things:

1. Append a number to the slug `the-2021-west-virginia-black-legislative-agenda-2`
2. Return an error and ask the user to adjust the slug.

**Comment by jacqui** [comment]
Returning an error seems like the most straightforward approach here.

So, this will require:

* [] write a query that looks up an article record for a given organization by category_id and slug
* [] call a function that does this lookup before doing the insert-or-update article: around here should be good https://github.com/news-catalyst/google-app-scripts/blob/552a06c752d070c98d496c174a44ff96ca08054e/Code.js#L433
* [] if any matching records are found, return a specific error with a message describing the problem
* add a check for error responses to where this function is called (both places need an error check anyway)
  * [] publishing: https://github.com/news-catalyst/google-app-scripts/blob/552a06c752d070c98d496c174a44ff96ca08054e/Code.js#L898
  * [] previewing: https://github.com/news-catalyst/google-app-scripts/blob/552a06c752d070c98d496c174a44ff96ca08054e/Code.js#L1065
* [] return the error message to the sidebar in both places
* [] display this error in the sidebar above the form
