### ISSUE TITLE
Publishing doesn't seem to do anything

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#84]
I tried to publish out of [this doc](https://docs.google.com/document/d/1hP_9DerDbLlQoR56JQ1w8k9OUIqg5h46z6uVVjNS1PA/edit?addon_dry_run=AAnXSK90-AWeHDHosJ2_22i1J-EvgID4JZTjVDxYXT0zYgN6CaMR-HJey7YSeuFuWitASBsK02G2ikO5W1EB_MUFPrejyh2F8c4zzpkgkhu4tw0W5SBfdDeA5y1j9iL-b1yQ3T0i1C4t), but I just see loading for minutes, and I don't see any functions fire in the logs past `getArticleMeta`. Not sure what's happening.

**Comment by jacqui** [comment]
I wrote up what caused this & the fix in the linked PR #87
