### ISSUE TITLE
Can we manually associate docs with articles?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#94]
Example: A freelancer writes a story, shares the doc with a Tiny News editor, and the Tiny News editor publishes out of that doc. Later, the freelancer deletes the original doc, but the editor wants to update the story. Could they create a new doc with the same content and associate the doc with the Webiny article manually?

**Comment by jacqui** [comment]
Closing this issue as this is largely done (after a week off, though, I'm trying to remember!) and any subsequent bugs or features can go into new issues...
